services:
  selenoid:
    container_name: selenoid-24
    network_mode: bridge
    image: aerokube/selenoid:latest-release
    volumes:
      - "./browsers.json:/etc/selenoid/browsers.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/home/selenoid/video" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    container_name: selenoid-ui-24
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    ports:
      - "8080:8080"
    links:
      - selenoid
    depends_on:
      - selenoid
    command: [ "--selenoid-uri", "http://selenoid-24:4444" ]

volumes:
  selenoid_storage: { }