
base.url=https://www.ozon.ru/

timeouts.factor=1.1f
#browser=selenoid
browser=chrome
#browser=chrome-headless
#browser=firefox
#browser=edge
download.path=target/downloads
archive.location=D:/downloads/TestRunArchive
screen.resolution=1920,1080